name: actions
on:
  push:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  pull_request:
    branches:
      - master
    paths:
      - containers/**
      - .github/workflows/actions.yml
      - "*.sh"
  workflow_dispatch:
jobs:
  qemu-user-static:
    runs-on: ubuntu-latest
    env:
      VERSION: 9.1.0-8
      ORIGIN_VERSION: 9.1.0+ds-8
      DOCKER_REPO: polyarch/qemu-user-static
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV
      - name: Build
        run: |
          wget --content-disposition https://ftp.debian.org/debian/pool/main/q/qemu/qemu-user_${{ env.ORIGIN_VERSION }}_amd64.deb
          dpkg-deb -v -R qemu-user_*.deb releases
          ./run.sh -t "${{ env.VERSION }}" -r "${{ env.GITHUB_REPOSITORY }}" -d "${{ env.DOCKER_REPO }}"
     #- name: Test
     #  run: ./test.sh -d "${{ env.DOCKER_REPO }}"
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push --all-tags ${{ env.DOCKER_REPO }}
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          body: |
            # `qemu-*` @ ${{ env.VERSION }}
          artifacts: "releases/usr/bin/*.tar.gz,releases/usr/bin/qemu-*"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
